# Configuration for repository.

graph:
    # Name of the "main" graph containing metadata about all resources.
    #
    # Default: main
    main_graph: main

# Configuration for binary path and fixity check generation. The hash is a
# checksumn of the contents of the file.
uuid:
    # Algorithm used to calculate the hash that generates the content path.
    # One of: sha1, sha224, sha256, sha384, or sha512, corresponding to the
    # omonymous hashlib function.
    #
    # Default: sha1.
    algo: sha1


# Data store configuration.
store:
    # The semantic store used for persisting LDP-RS (RDF Source) resources.
    # MUST support SPARQL 1.1 query and update.
    ldp_rs:
        # Store layout. This corresponds to a sub-class of the
        # `lakesuperior.store_layouts.rdf.base_rdf_layout/BaseRdfLayout`.
        layout: simple_layout
        webroot: http://localhost:9999/namespace/fcrepo/
        query_ep: sparql
        update_ep: sparql
        default_graph: http://www.w3.org/ns/sparql-service-description#
        # Optional
        username: <set me>
        password: <set me>
        ssl_verify: false

    # The path used to persist LDP-NR (bitstreams).
    # This is for now a POSIX filesystem. Other solutions such as HDFS may be
    # possible in the future.
    ldp_nr:
        # The filesystem path to the root of the binary store.
        path: /data/fcrepo/ldpnr_store

        # How to split the balanced pairtree to generate a path. The hash
        # string is defined by the uuid.algo parameter value.
        # This parameter defines how many characters are in each branch. 2-4 is
        # the recommended setting. NOTE: a value of 2 will generate up to 256
        # sub-folders in a folder; 3 will generate max. 4096 and 4 will
        # generate max. 65536. Check your filesystem capabilities before
        # setting this to a non-default value.
        #
        # Default: 2
        pairtree_branch_length: 2

        # Max. number of branches to generate. 0 will split the string until
        # it reaches the end.
        # E.g. if the hash value is 01234567-89ab-cdef-0123-4565789abcdef
        # (dashes added for readability), and the branch length value is 2, and
        # the branch number is 4, the path will be 
        # 01/23/45/67/89abcdef01234565789abcdef. For a value of 0 it will be
        # 01/23/45/67/89/ab/cd/ef/01/23/45/67/89/ab/cd/ef. Check your system
        # capabilities for maximum nested directories before setting this to 0,
        # especially with longer hash algorithms.
        #
        # Default: 4
        pairtree_branches: 4

